spring.application.name=exam
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/exam}
spring.datasource.username=${DB_USERNAME:exam}
spring.datasource.password=${DB_PASSWORD:exam}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
