server.port=8090
spring.application.name=exam
spring.datasource.url=${DB_URL:jdbc:postgresql://172.24.144.1:5432/exam}
spring.datasource.username=${DB_USERNAME:exam}
spring.datasource.password=${DB_PASSWORD:exam}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:create}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Set this to an authorized exam JSON file path to import it on startup.
# app.import.exam-json=./data/exam-import.json
app.import.skip-existing-title=true
